//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.DlyaPrilozheniya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Получение.
    /// </summary>
    // *** Start programmer edit section *** (Получение CustomAttributes)

    // *** End programmer edit section *** (Получение CustomAttributes)
    public enum Получение
    {
        
        // *** Start programmer edit section *** (Получение.Самовывоз CustomAttributes)

        // *** End programmer edit section *** (Получение.Самовывоз CustomAttributes)
        [Caption("Самовывоз")]
        Самовывоз,
        
        // *** Start programmer edit section *** (Получение.Доставка CustomAttributes)

        // *** End programmer edit section *** (Получение.Доставка CustomAttributes)
        [Caption("Доставка")]
        Доставка,
    }
}
