//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.DlyaPrilozheniya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Складское место.
    /// </summary>
    // *** Start programmer edit section *** (СкладскоеМесто CustomAttributes)

    // *** End programmer edit section *** (СкладскоеМесто CustomAttributes)
    [AutoAltered()]
    [Caption("Складское место")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СкладскоеМестоE", new string[] {
            "НомерМеста as \'Номер места\'",
            "Расшифровка as \'Расшифровка\'"})]
    [View("СкладскоеМестоL", new string[] {
            "НомерМеста as \'Номер места\'",
            "Расшифровка as \'Расшифровка\'"})]
    public class СкладскоеМесто : ICSSoft.STORMNET.DataObject
    {
        
        private string fНомерМеста;
        
        private string fРасшифровка;
        
        // *** Start programmer edit section *** (СкладскоеМесто CustomMembers)

        // *** End programmer edit section *** (СкладскоеМесто CustomMembers)

        
        /// <summary>
        /// НомерМеста.
        /// </summary>
        // *** Start programmer edit section *** (СкладскоеМесто.НомерМеста CustomAttributes)

        // *** End programmer edit section *** (СкладскоеМесто.НомерМеста CustomAttributes)
        [StrLen(255)]
        public virtual string НомерМеста
        {
            get
            {
                // *** Start programmer edit section *** (СкладскоеМесто.НомерМеста Get start)

                // *** End programmer edit section *** (СкладскоеМесто.НомерМеста Get start)
                string result = this.fНомерМеста;
                // *** Start programmer edit section *** (СкладскоеМесто.НомерМеста Get end)

                // *** End programmer edit section *** (СкладскоеМесто.НомерМеста Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СкладскоеМесто.НомерМеста Set start)

                // *** End programmer edit section *** (СкладскоеМесто.НомерМеста Set start)
                this.fНомерМеста = value;
                // *** Start programmer edit section *** (СкладскоеМесто.НомерМеста Set end)

                // *** End programmer edit section *** (СкладскоеМесто.НомерМеста Set end)
            }
        }
        
        /// <summary>
        /// Расшифровка.
        /// </summary>
        // *** Start programmer edit section *** (СкладскоеМесто.Расшифровка CustomAttributes)

        // *** End programmer edit section *** (СкладскоеМесто.Расшифровка CustomAttributes)
        [StrLen(255)]
        public virtual string Расшифровка
        {
            get
            {
                // *** Start programmer edit section *** (СкладскоеМесто.Расшифровка Get start)

                // *** End programmer edit section *** (СкладскоеМесто.Расшифровка Get start)
                string result = this.fРасшифровка;
                // *** Start programmer edit section *** (СкладскоеМесто.Расшифровка Get end)

                // *** End programmer edit section *** (СкладскоеМесто.Расшифровка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СкладскоеМесто.Расшифровка Set start)

                // *** End programmer edit section *** (СкладскоеМесто.Расшифровка Set start)
                this.fРасшифровка = value;
                // *** Start programmer edit section *** (СкладскоеМесто.Расшифровка Set end)

                // *** End programmer edit section *** (СкладскоеМесто.Расшифровка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СкладскоеМестоE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СкладскоеМестоE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СкладскоеМестоE", typeof(IIS.DlyaPrilozheniya.СкладскоеМесто));
                }
            }
            
            /// <summary>
            /// "СкладскоеМестоL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СкладскоеМестоL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СкладскоеМестоL", typeof(IIS.DlyaPrilozheniya.СкладскоеМесто));
                }
            }
        }
    }
}
